# =================================================================
#
# Copyright (C) 2021 Spatial Current, Inc. - All Rights Reserved
# Released as open source under the MIT License.  See LICENSE file.
#
# =================================================================
version: "2.1"

executors:
  main:
    docker:
      - image: cimg/python:3.9.7-node

jobs:

  test:
    executor: main
    steps:
      - checkout
      - run: python --version
      - run: pipenv install
      - run: pipenv install flake8
      - run: pipenv run flake8 setup.py geocrypt
      - run: python -m unittest geocrypt.test

workflows:
  version: 2
  main:
    jobs:
      - test
